
sp:
  user-service:
    users: "[{\"id\":17, \"username\":\"abc\",\"password\":\"123\"},{\"id\":18, \"username\":\"def\",\"password\":\"456\"},{\"id\":19, \"username\":\"ghi\",\"password\":\"789\"}]"

spring:
  application:
    name: user-service
    
server:
  port: 8101
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka1:2002/eureka  #向eureka服务中心注册
 
management:
  endpoints:
    web:
      exposure:
        include: refresh
